spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/scleraintern?user=root&password=25274
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
app.jwt.secret=ThisIsAVeryStrongSecretKeyForJwtSigning1234567890
app.jwt.expiration-ms=86400000
openlibrary.base-url=https://openlibrary.org
openlibrary.search-path=/search.json
openlibrary.default-limit=10
openlibrary.max-limit=50